### ISSUE TITLE
visualization of inertia ellipsoids

### ISSUE THREAD

**Issue by shivesh1210** [ROAM-Lab-ND/inertia_identification_minimal_examples#2]
It would be helpful if we can visualize the inertia ellipsoid along with leg design as shown in Fig. 7 of the paper here: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8922724. Could you please add the code for it as well in the main script?

**Comment by shivesh1210** [comment]
Also, see https://github.com/alex07143/Geometric-Robot-DynID/blob/master/main.m#L53 for the visualization code in the repo provided with the paper (https://github.com/alex07143/Geometric-Robot-DynID).

**Comment by pwensing** [comment]
Should be all set! Thanks, @alex07143 for the assist!
Please let me know if it gives you any issues.

**Comment by shivesh1210** [comment]
@pwensing AdjointToSE3 method is missing. Here is the error output:

Unrecognized function or variable 'AdjointToSE3'.

Error in Cheetah_bound_visualize (line 40)
      T    = inv( AdjointToSE3( X0{i} ) );

Error in main (line 83)
Cheetah_bound_visualize(obj, Q_bound, color)

**Comment by pwensing** [comment]
@shivesh1210 it looks like this is an issue with your `spatial_v2_extended` submodule not updating when you pulled down the updated repo. I believe you should be able to fix this by running `git submodule update`. 

As of git 2.16, you can setup your `pull` behavior to automatically update submodules too via `git config --global submodule.recurse true`. See, also, the discussion over at https://stackoverflow.com/questions/4611512/is-there-a-way-to-make-git-pull-automatically-update-submodules

Please let me know if this fixes it for you.

**Comment by pwensing** [comment]
@shivesh1210 it looks like this is an issue with your `spatial_v2_extended` submodule not updating when you pulled down the updated repo. I believe you should be able to fix this by running `git submodule update`. 

As of git 2.16, you can setup your `pull` behavior to automatically update submodules too via `git config --global submodule.recurse true`. See, also, the discussion over at https://stackoverflow.com/questions/4611512/is-there-a-way-to-make-git-pull-automatically-update-submodules

Please let me know if this fixes it for you.

**Comment by shivesh1210** [comment]
@pwensing Yes, you are right. Thanks for your quick response. It works for me now. Closing the issue.
