### ISSUE TITLE
Unrecognized Variable error

### ISSUE THREAD

**Issue by JonasHaack** [ROAM-Lab-ND/inertia_identification_minimal_examples#3]
Hello,
when running the identification with constant pullback approximation, there occurs an "unrecognized function or variable" error.
I set the variable **use_const_pullback_approx = 1;** in line 100 of main.m. The error occurs in line 125. **prior_params(:,i)** is not defined. It appears, in fact, only in this specific line of the code. Is **prior_params(:,i)** supposed to be **pi_prior(:,i)**?
Thanks in advance for your help.

**Comment by pwensing** [comment]
You're 100% correct. Thanks for catching this issue. It should be fixed in a3bccd6eabf862cf648adc9614390fd49605c46d.

Can you please pull down and confirm that that fixes it for you?

Best,
-Pat

**Comment by JonasHaack** [comment]
Thank you very much. Now it works as expected.
Best,
Jonas
